jobs:
  build:
    name: Java ${{ matrix.java }} ${{ matrix.os }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: gradle/wrapper-validation-action@v2
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: corretto
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Clean, build and javadoc
      run: ./gradlew clean build javadoc -Plog-tests --stacktrace
    - continue-on-error: true
      if: matrix.os == 'windows-latest'
      name: Allow long file names in git for windows
      run: git config --system core.longpaths true
    - continue-on-error: true
      if: matrix.java == 17
      name: CLI integration tests
      run: ./gradlew :smithy-cli:integ -Plog-tests --stacktrace
    - continue-on-error: true
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: java-${{ matrix.java }}-${{ matrix.os }}-test-report
        path: '**/build/reports/tests'
    strategy:
      matrix:
        java:
        - 8
        - 11
        - 17
        - 21
        os:
        - macos-latest
        - ubuntu-latest
        - windows-latest
  build-docs:
    name: Documentation Build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - continue-on-error: true
      name: Install doc dependencies
      run: cd docs && make install
    - continue-on-error: true
      name: Build docs
      run: cd docs && make html
    - continue-on-error: true
      uses: actions/upload-artifact@v4
      with:
        name: built-docs
        path: docs/build/html
name: ci
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
