jobs:
  CodeGuruReviewerScan:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: iam-role
      name: Assume IAM Role
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-west-2
        role-to-assume: arn:aws:iam::048169001733:role/GuruGitHubCICDRole
    - continue-on-error: true
      if: steps.iam-role.outcome == 'success'
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      if: steps.iam-role.outcome == 'success'
      name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        distribution: corretto
        java-version: 8
    - continue-on-error: true
      if: steps.iam-role.outcome == 'success'
      name: Compile
      run: ./gradlew compileJava -x test
    - continue-on-error: true
      if: steps.iam-role.outcome == 'success'
      name: Copy build artifacts
      run: "mkdir -p class-files\ncp -r smithy-*/build/classes/java/main/* class-files\
        \ \n"
    - continue-on-error: true
      id: guruscan
      if: steps.iam-role.outcome == 'success'
      name: Run CodeGuru Reviewer
      uses: aws-actions/codeguru-reviewer@v1.1
      with:
        build_path: ./class-files
        s3_bucket: codeguru-reviewer-github-profiler-demo-048169001733-uw2
    - continue-on-error: true
      if: steps.iam-role.outcome == 'success' &&steps.guruscan.outcome == 'success'
      name: Upload review result
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: codeguru-results.sarif.json
name: Analyze with CodeGuru Reviewer
on:
  repository_dispatch:
    types: trigger-ga___codeguru-reviewer.yml
permissions:
  contents: read
  id-token: write
  security-events: write
