env:
  ARTIFACTS_DIR: /tmp/artifacts
jobs:
  build-docs:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repo
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup
      run: 'mkdir -p $ARTIFACTS_DIR

        '
    - continue-on-error: true
      if: ${{ !contains(inputs.javadocs, 'false') }}
      name: Build JavaDocs
      run: 'VERSION=$(cat VERSION)

        mkdir -p $ARTIFACTS_DIR/javadoc

        ./gradlew javadoc

        cp -R build/docs/javadoc/latest $ARTIFACTS_DIR/javadoc/$VERSION

        mkdir $ARTIFACTS_DIR/javadoc/latest

        cat << EOF > $ARTIFACTS_DIR/javadoc/latest/index.html

        <!DOCTYPE html>

        <meta charset="utf-8">

        <title>Redirecting to latest javadocs</title>

        <meta http-equiv="refresh" content="0; URL=../${VERSION}/">

        EOF

        '
    - continue-on-error: true
      name: Build Smithy docs
      run: 'cd docs

        pip3 install -r requirements.txt

        make clean

        make html

        cp -R build/html/* $ARTIFACTS_DIR

        rm $ARTIFACTS_DIR/.buildinfo || true

        rm $ARTIFACTS_DIR/objects.inv || true

        '
    - continue-on-error: true
      name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: smithy-docs
        path: ${{ env.ARTIFACTS_DIR }}
        retention-days: 7
  publish-docs:
    if: ${{ !contains(inputs.release, 'false') }}
    needs: build-docs
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout GitHub pages branch
      uses: actions/checkout@v4
      with:
        ref: gh-pages
    - continue-on-error: true
      id: download
      name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: smithy-docs
        path: /tmp/smithy-docs
    - continue-on-error: true
      name: Copy artifacts
      run: 'git pull

        cp -R /tmp/smithy-docs/* .

        git config --global user.name "smithy-automation"

        git config --global user.email "github-smithy-automation@amazon.com"

        git add -A

        git commit -m "Update documentation"

        git push

        '
name: make-docs
on:
  repository_dispatch:
    types: trigger-ga___make-docs.yml
