jobs:
  build-aws-sdk-go-v2:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: corretto
        java-version: 17
    - continue-on-error: true
      name: Set up Go 1.19
      uses: actions/setup-go@v5
      with:
        go-version: 1.19
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      id: smithy-version
      uses: ./.github/workflows/checkout-and-build-smithy
    - continue-on-error: true
      name: Add smithyVersion env variable
      run: echo "smithyVersion=${{ steps.smithy-version.outputs.smithy-version }}"
        >> $GITHUB_ENV
    - continue-on-error: true
      name: Checkout smithy-go
      uses: actions/checkout@v4
      with:
        path: smithy-go
        repository: aws/smithy-go
    - continue-on-error: true
      name: Build smithy-go
      run: cd smithy-go/codegen && ./gradlew -PsmithyVersion=$smithyVersion clean
        build publishToMavenLocal
    - continue-on-error: true
      name: Checkout aws-sdk-go-v2
      uses: actions/checkout@v4
      with:
        path: aws-sdk-go-v2
        repository: aws/aws-sdk-go-v2
    - continue-on-error: true
      name: Build aws-sdk-go-v2
      run: 'cd aws-sdk-go-v2/codegen

        ./gradlew -PsmithyVersion=$smithyVersion clean build -Plog-tests

        ./gradlew clean

        '
    - continue-on-error: true
      name: Run aws-sdk-go-v2 protocol tests
      run: 'cd aws-sdk-go-v2 && make update-requires gen-repo-mod-replace \

        update-module-metadata smithy-annotate-stable gen-config-asserts gen-internal-codegen
        \

        copy-attributevalue-feature gen-mod-dropreplace-smithy-. min-go-version-.
        tidy-modules-. \

        add-module-license-files gen-aws-ptrs format unit-race ci-test-generate-validate

        '
  build-aws-sdk-js-v3:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Use Node.js 14.x
      uses: actions/setup-node@v4
      with:
        node-version: 14.x
    - continue-on-error: true
      name: Increase Node Heap space
      run: echo "NODE_OPTIONS=--max-old-space-size=16384" >> $GITHUB_ENV
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      id: smithy-version
      uses: ./.github/workflows/checkout-and-build-smithy
    - continue-on-error: true
      name: Add smithyVersion env variable
      run: echo "smithyVersion=${{ steps.smithy-version.outputs.smithy-version }}"
        >> $GITHUB_ENV
    - continue-on-error: true
      name: Checkout smithy-typescript
      uses: actions/checkout@v4
      with:
        path: smithy-typescript
        repository: awslabs/smithy-typescript
    - continue-on-error: true
      name: Build smithy-typescript
      run: cd smithy-typescript && ./gradlew -PsmithyVersion=$smithyVersion clean
        build publishToMavenLocal
    - continue-on-error: true
      name: Checkout aws-sdk-js-v3
      uses: actions/checkout@v4
      with:
        path: aws-sdk-js-v3
        repository: aws/aws-sdk-js-v3
    - continue-on-error: true
      name: Build aws-sdk-js-v3
      run: cd aws-sdk-js-v3/codegen && ./gradlew -PsmithyVersion=$smithyVersion clean
        build
    - continue-on-error: true
      name: Test aws-sdk-js-v3
      run: cd aws-sdk-js-v3 && yarn && yarn test:all
  build-aws-sdk-kotlin:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      id: smithy-version
      uses: ./.github/workflows/checkout-and-build-smithy
    - continue-on-error: true
      name: Add smithyVersion env variable
      run: echo "smithyVersion=${{ steps.smithy-version.outputs.smithy-version }}"
        >> $GITHUB_ENV
    - continue-on-error: true
      name: Checkout smithy-kotlin
      uses: actions/checkout@v4
      with:
        path: smithy-kotlin
        repository: awslabs/smithy-kotlin
    - continue-on-error: true
      name: Build smithy-kotlin
      run: cd smithy-kotlin && ./gradlew -PsmithyVersion=$smithyVersion clean build
        publishToMavenLocal
    - continue-on-error: true
      name: Checkout aws-sdk-kotlin
      uses: actions/checkout@v4
      with:
        path: aws-sdk-kotlin
        repository: awslabs/aws-sdk-kotlin
    - continue-on-error: true
      name: Build aws-sdk-kotlin
      run: cd aws-sdk-kotlin && ./gradlew -PsmithyVersion=$smithyVersion clean build
    - continue-on-error: true
      name: Build aws-sdk-kotlin
      run: cd aws-sdk-kotlin && ./gradlew -PsmithyVersion=$smithyVersion clean build
        publishToMavenLocal
    - continue-on-error: true
      name: Run aws-sdk-kotlin protocol tests
      run: cd aws-sdk-kotlin && ./gradlew -PsmithyVersion=$smithyVersion -p codegen/protocol-tests
        testAllProtocols
  build-aws-sdk-swift:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: swift-actions/setup-swift@v2
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: corretto
        java-version: 11
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      id: smithy-version
      uses: ./.github/workflows/checkout-and-build-smithy
    - continue-on-error: true
      name: Add smithyVersion env variable
      run: echo "smithyVersion=${{ steps.smithy-version.outputs.smithy-version }}"
        >> $GITHUB_ENV
    - continue-on-error: true
      name: Checkout aws-crt-swift
      uses: actions/checkout@v4
      with:
        path: Sources/SmithySwift/aws-crt-swift
        repository: awslabs/aws-crt-swift
    - continue-on-error: true
      name: Checkout smithy-swift
      uses: actions/checkout@v4
      with:
        path: Sources/SmithySwift/smithy-swift
        repository: awslabs/smithy-swift
    - continue-on-error: true
      name: Build smithy-swift
      run: 'echo $smithyVersion && cd Sources/SmithySwift/smithy-swift

        ./gradlew -PsmithyVersion=$smithyVersion clean build publishToMavenLocal

        '
    - continue-on-error: true
      name: Checkout aws-sdk-swift
      uses: actions/checkout@v4
      with:
        path: Sources/SmithySwift/aws-sdk-swift
        repository: awslabs/aws-sdk-swift
    - continue-on-error: true
      name: Set SMITHY_SWIFT_CI_DIR env variable
      run: echo "SMITHY_SWIFT_CI_DIR=$GITHUB_WORKSPACE/Sources/SmithySwift/smithy-swift"
        >> $GITHUB_ENV
    - continue-on-error: true
      name: Set AWS_SDK_SWIFT_CI_DIR env variable
      run: echo "AWS_SDK_SWIFT_CI_DIR=$GITHUB_WORKSPACE/Sources/SmithySwift/aws-sdk-swift"
        >> $GITHUB_ENV
    - continue-on-error: true
      name: Build aws-sdk-swift
      run: cd Sources/SmithySwift/aws-sdk-swift && ./gradlew -PsmithyVersion=$smithyVersion
        clean build
    - continue-on-error: true
      name: Generate Swift SDKs
      run: cd Sources/SmithySwift/aws-sdk-swift && ./gradlew -PsmithyVersion=$smithyVersion
        -p codegen/sdk-codegen build
    - continue-on-error: true
      name: Build codegen/protocol-test-codegen-local
      run: cd Sources/SmithySwift/aws-sdk-swift && ./gradlew -PsmithyVersion=$smithyVersion
        -p codegen/protocol-test-codegen-local build
    - continue-on-error: true
      name: Run local protocol tests
      run: cd Sources/SmithySwift/aws-sdk-swift/codegen/protocol-test-codegen-local/build
        && swift test
  build-smithy-rs:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Set up Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: 1.62.1
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: corretto
        java-version: 11
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      id: smithy-version
      uses: ./.github/workflows/checkout-and-build-smithy
    - continue-on-error: true
      name: Add smithyVersion env variable
      run: echo "smithyVersion=${{ steps.smithy-version.outputs.smithy-version }}"
        >> $GITHUB_ENV
    - continue-on-error: true
      name: Check out smithy-rs
      uses: actions/checkout@v4
      with:
        path: smithy-rs
        ref: main
        repository: awslabs/smithy-rs
    - continue-on-error: true
      name: Check out aws-sdk-rust
      uses: actions/checkout@v4
      with:
        path: aws-sdk-rust
        ref: main
        repository: awslabs/aws-sdk-rust
    - continue-on-error: true
      name: Install rustfmt
      run: rustup component add rustfmt
    - continue-on-error: true
      name: Build smithy-rs
      run: 'cd smithy-rs

        ./gradlew :aws:sdk:assemble -PsmithyVersion=$smithyVersion

        '
    - continue-on-error: true
      name: Test smithy-rs
      run: 'cd smithy-rs

        ./gradlew :aws:sdk:cargoTest -PsmithyVersion=$smithyVersion

        '
name: sdk-codegen-ci
on:
  repository_dispatch:
    types: trigger-ga___sdk-codegen-ci.yml
