jobs:
  cleanup:
    name: Stale issue job
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: aws-actions/stale-issue-cleanup@v6
      with:
        ancient-issue-message: "We\u2019re closing this issue because it has been\
          \ open a long time and hasn\u2019t been updated in a while and may not be\
          \ getting the attention it deserves. We encourage you to check if this is\
          \ still an issue in the latest release and if you find that this is still\
          \ a problem, please feel free to comment or open a new issue."
        closed-for-staleness-label: closed-for-staleness
        days-before-ancient: 365
        days-before-close: 14
        days-before-stale: 60
        exempt-issue-labels: bug,documentation,feature-request,investigating,protocol-test
        issue-types: issues
        loglevel: DEBUG
        minimum-upvotes-to-exempt: 5
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        response-requested-label: response-requested
        stale-issue-label: closing-soon
        stale-issue-message: This issue has not received a response in a while. If
          you still think there is a problem, please leave a comment to avoid the
          issue from automatically closing.
name: Close stale issues
on:
  repository_dispatch:
    types: trigger-ga___stale-issues.yml
