env:
  release_prefix: https://github.com/smithy-lang/smithy/releases/download
jobs:
  create-pr:
    needs: download-and-save
    permissions:
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: download
      name: Get artifacts
      uses: actions/download-artifact@v4
      with:
        name: brew-artifacts
    - continue-on-error: true
      name: Checkout bottle repo
      uses: actions/checkout@v4
      with:
        path: homebrew-tap
        ref: main
        repository: smithy-lang/homebrew-tap
        token: ${{ secrets.PR_TOKEN }}
    - continue-on-error: true
      name: Update version
      run: 'version="${GITHUB_REF##*/}"

        tmp=$(mktemp)

        jq --arg version "${version}" ''.version = $version'' homebrew-tap/bottle-configs/smithy-cli.json
        > "$tmp" && mv "$tmp" homebrew-tap/bottle-configs/smithy-cli.json

        '
    - continue-on-error: true
      name: Update root_url
      run: 'version="${GITHUB_REF##*/}"

        tmp=$(mktemp)

        jq --arg release_url "${{ env.release_prefix }}" --arg version "${version}"
        ''.bottle.root_url = "\($release_url)/\($version)/smithy-cli"'' homebrew-tap/bottle-configs/smithy-cli.json
        > "$tmp" && mv "$tmp" homebrew-tap/bottle-configs/smithy-cli.json

        '
    - continue-on-error: true
      name: Update mac
      run: 'version="${GITHUB_REF##*/}"

        sha=$(cut -d " " -f1 ${{steps.download.outputs.download-path}}/smithy-cli-darwin-x86_64.tar.gz.sha256)

        tmp=$(mktemp)

        jq --arg sha "$sha" ''.bottle.sha256.sierra = "''$sha''"'' homebrew-tap/bottle-configs/smithy-cli.json
        > "$tmp" && mv "$tmp" homebrew-tap/bottle-configs/smithy-cli.json

        '
    - continue-on-error: true
      name: Update mac-arm
      run: 'version="${GITHUB_REF##*/}"

        sha=$(cut -d " " -f1 ${{steps.download.outputs.download-path}}/smithy-cli-darwin-aarch64.tar.gz.sha256)

        tmp=$(mktemp)

        jq --arg sha "$sha" ''.bottle.sha256.arm64_big_sur = "''$sha''"'' homebrew-tap/bottle-configs/smithy-cli.json
        > "$tmp" && mv "$tmp" homebrew-tap/bottle-configs/smithy-cli.json

        '
    - continue-on-error: true
      name: Update linux
      run: 'version="${GITHUB_REF##*/}"

        sha=$(cut -d " " -f1 ${{steps.download.outputs.download-path}}/smithy-cli-linux-x86_64.tar.gz.sha256)

        tmp=$(mktemp)

        jq --arg sha "$sha" ''.bottle.sha256.linux = "''$sha''"'' homebrew-tap/bottle-configs/smithy-cli.json
        > "$tmp" && mv "$tmp" homebrew-tap/bottle-configs/smithy-cli.json

        '
    - continue-on-error: true
      name: Update linux-arm
      run: 'version="${GITHUB_REF##*/}"

        sha=$(cut -d " " -f1 ${{steps.download.outputs.download-path}}/smithy-cli-linux-aarch64.tar.gz.sha256)

        tmp=$(mktemp)

        jq --arg sha "$sha" ''.bottle.sha256.linux_arm = "''$sha''"'' homebrew-tap/bottle-configs/smithy-cli.json
        > "$tmp" && mv "$tmp" homebrew-tap/bottle-configs/smithy-cli.json

        '
    - continue-on-error: true
      name: Set up new git branch for version bump
      run: 'git config user.name ''smithy-automation''

        git config user.email ''github-smithy-automation@amazon.com''

        git checkout -b "automation/bump-smithy-cli-version/${GITHUB_REF##*/}"

        '
      working-directory: homebrew-tap
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.PR_TOKEN }}
      name: Create PR
      run: "git add bottle-configs/smithy-cli.json\ngit commit -m \"chore: upgrade\
        \ smithy-cli to ${GITHUB_REF##*/}\"\ngit push --set-upstream origin \"automation/bump-smithy-cli-version/${GITHUB_REF##*/}\"\
        \ngh pr create \\\n  --title \"[Automation] chore: upgrade smithy-cli to ${GITHUB_REF##*/}\"\
        \ \\\n  --body \"Created by ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}\"\
        \ \\\n  --base main\n"
      working-directory: homebrew-tap
  download-and-save:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: startsWith(github.ref, 'refs/tags/')
      name: mac
      run: 'version="${GITHUB_REF##*/}"

        hash_url="${{ env.release_prefix }}/${version}/smithy-cli-darwin-x86_64.tar.gz"

        echo $hash_url

        curl -fJLO $hash_url.sha256

        '
    - continue-on-error: true
      if: startsWith(github.ref, 'refs/tags/')
      name: mac-arm
      run: 'version="${GITHUB_REF##*/}"

        hash_url="${{ env.release_prefix }}/${version}/smithy-cli-darwin-aarch64.tar.gz"

        echo $hash_url

        curl -fJLO $hash_url.sha256

        '
    - continue-on-error: true
      if: startsWith(github.ref, 'refs/tags/')
      name: linux
      run: 'version="${GITHUB_REF##*/}"

        hash_url="${{ env.release_prefix }}/${version}/smithy-cli-linux-x86_64.tar.gz"

        echo $hash_url

        curl -fJLO $hash_url.sha256

        '
    - continue-on-error: true
      if: startsWith(github.ref, 'refs/tags/')
      name: linux-arm
      run: 'version="${GITHUB_REF##*/}"

        hash_url="${{ env.release_prefix }}/${version}/smithy-cli-linux-aarch64.tar.gz"

        echo $hash_url

        curl -fJLO $hash_url.sha256

        '
    - continue-on-error: true
      name: Save artifacts
      uses: actions/upload-artifact@v4
      with:
        name: brew-artifacts
        path: '*.sha256'
        retention-days: 7
name: update-brew
on:
  repository_dispatch:
    types: trigger-ga___update-brew.yml
