jobs:
  get-version:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      id: fetch-latest
      name: Fetch latest smithy-gradle-plugin version
      run: "echo \"latestSmithyGradle=$( \\\n curl -sL https://api.github.com/repos/smithy-lang/smithy-gradle-plugin/tags\
        \ | \\\n jq -r '.[0].name')\" >> $GITHUB_OUTPUT\n"
    - continue-on-error: true
      id: get-current
      name: Get current version
      run: 'cat gradle.properties >> $GITHUB_OUTPUT

        '
    - continue-on-error: true
      id: update-check
      name: Check if the current version of smithy-gradle-plugin should be updated
      run: 'echo update-required=$( \

        [ "${{ steps.get-current.outputs.smithyGradleVersion }}" = "${{ steps.fetch-latest.outputs.latestSmithyGradle
        }}" ] \

        && echo "false" || echo "true") >> $GITHUB_OUTPUT

        '
    - continue-on-error: true
      id: git-setup
      if: steps.update-check.outputs.update-required == 'true'
      name: Set up new git branch for version bump
      run: 'git checkout -b "automation/bump-smithy-gradle-version/${{ steps.fetch-latest.outputs.latestSmithyGradle
        }}"

        git config --global user.email "github-aws-smithy-automation@amazon.com"

        git config --global user.name "Smithy Automation"

        '
    - continue-on-error: true
      id: replace-current-version-properties
      if: steps.update-check.outputs.update-required == 'true'
      name: Find and replace gradle version in properties files
      run: 'find . -type f -name ''gradle.properties'' \

        -exec sed -i "s|smithyGradleVersion=${{ steps.get-current.outputs.smithyGradleVersion
        }}|smithyGradleVersion=${{ steps.fetch-latest.outputs.latestSmithyGradle }}|g"
        {} \;

        '
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.PR_TOKEN }}
      if: steps.update-check.outputs.update-required == 'true'
      name: Create PR
      run: "git add .\ngit commit -m 'Update smithy-gradle-plugin Version'\ngit push\
        \ --set-upstream origin \"automation/bump-smithy-gradle-version/${{ steps.fetch-latest.outputs.latestSmithyGradle\
        \ }}\"\ngh pr create \\\n  --title \"[Automation] smithy-gradle-plugin Version\
        \ Bump - \\`${{ steps.fetch-latest.outputs.latestSmithyGradle }}\\`\" \\\n\
        \  --body \"Automated pull request to bump smithy gradle plugin version from\
        \ ${{ steps.get-current.outputs.smithyGradleVersion }} to ${{ steps.fetch-latest.outputs.latestSmithyGradle\
        \ }}\" \\\n  --base main\necho \"PR Created for version bump to ${{ steps.fetch-latest.outputs.latestSmithyGradle\
        \ }}\"\n"
name: Get latest smithy gradle plugin version
on:
  repository_dispatch:
    types: trigger-ga___update-gradle-plugin.yml
